---
- name: setup Mysql with medium_db db and remote login
  hosts: server

  tasks:
    - name: Ansible apt-get to get install mysql
      become: true
      apt:
        name:
          - python3-pip
          - mysql-server
        state: present
        force_apt_get: yes